version: '3.8'

services:
  db:
    image: mongo:latest
    container_name: befit-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  backend:
    build: ./backend
    container_name: befit-backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017/
    volumes:
      - ./ai_model:/ai_model
    restart: always

  frontend:
    build: ./frontend
    container_name: befit-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:8000
    restart: always

volumes:
  mongo_data:
